server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: funding_route
          uri: http://localhost:8081
          predicates:
            - Path=/fundings/**
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG


